/* eslint-disable react/jsx-no-comment-textnodes */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 RhinoModel0316.glb
*/

import React, { useRef } from "react";
import { useGLTF, Edges, shaderMaterial } from "@react-three/drei";
import { EffectComposer, Outline, Select } from "@react-three/postprocessing";
import { Color, ShaderMaterial } from "three";
import { useControls, folder } from "leva";
import { extend } from "@react-three/fiber";

const CustomCenterShaderMaterial = shaderMaterial(
  {
    time: 0,
    opacity: 0.1,
  },
  `
    void main() {
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  `
    uniform float time;
    uniform float opacity;
    void main() {
      gl_FragColor = vec4(0.8, 0.8, 0.0, opacity);
    }
    `
);
const CustomOtherShaderMaterial = shaderMaterial(
  {
    time: 0,
    opacity: 0.1,
  },
  `
    void main() {
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  `
    uniform float time;
    uniform float opacity;
    void main() {
      gl_FragColor += vec4(0.5, 0.5, 0.5, 1.0) * sin(time * 2.0);
    }
    `
);

// gl_FragColor = vec4(0.1, 0.1, 0.1, opacity);

extend({ CustomCenterShaderMaterial, CustomOtherShaderMaterial });

export default function RhinoModel0316({ ...props }) {
  const { nodes, materials, scene } = useGLTF("models/RhinoModel0316.glb");
  const meshes = Object.values(nodes).filter((n) => n.type === "Mesh");
  const group = useRef();
  const config = useControls({
    parts: folder(
      {
        center: { value: true },
        // tower: { value: true },
        building: { value: false },
      },
      { collapsed: true }
    ),
  });

  // 设置模型的材质和阴影属性
  scene.traverse((child) => {
    if (child.isMesh) {
      child.castShadow = true;
      child.receiveShadow = true;
      child.material.side = 2; // 设置材质为双面显示
    }
  });

  console.log("meshes", meshes);
  console.log("nodes", nodes);
  console.log("materials", materials);
  console.log("scene", scene);

  return (
    <group ref={group} {...props} dispose={null} castShadow receiveShadow>
      //site
      <mesh
        geometry={nodes.site.geometry}
        material={materials["site"]}
        castShadow
        receiveShadow
      >
        <Edges scale={1} threshold={15} color="#F00" lineWidth={20} />
      </mesh>
      <Select enabled={config.all}>
        <Select name="center" enabled={config.center}>
          //skirt
          {meshes
            .filter((v) => v.name.includes("skirt"))
            .map((item, index) => {
              return (
                <mesh
                  key={index}
                  geometry={item.geometry}
                  castShadow
                  receiveShadow
                >
                  <meshStandardMaterial
                    transparent
                    opacity={0.7}
                    color="#F0F"
                  />
                  {/* <customOtherShaderMaterial attach="material" /> */}
                  <Edges scale={1} threshold={15} color="#000" />
                </mesh>
              );
            })}
          //tower
          {meshes
            .filter((v) => v.name.includes("tower"))
            .map((item, index) => {
              return (
                <mesh
                  key={index}
                  geometry={item.geometry}
                  castShadow
                  receiveShadow
                >
                  <meshStandardMaterial
                    transparent
                    opacity={0.7}
                    color="#FF0"
                  />
                  <Edges scale={1} threshold={15} color="#000" />
                </mesh>
              );
            })}
        </Select>
        <Select name="building" enabled={config.building}>
          //building
          {meshes
            .filter((v) => v.name.includes("building"))
            .map((item, index) => {
              return (
                <mesh
                  key={index}
                  geometry={item.geometry}
                  castShadow
                  receiveShadow
                >
                  <meshStandardMaterial
                    transparent
                    opacity={0.7}
                    color="#234"
                  />
                  {/* <customOtherShaderMaterial attach="material" /> */}
                  <Edges scale={1} threshold={15} color="#AAA" />
                </mesh>
              );
            })}
          {/* <mesh
            geometry={nodes.building.geometry}
            // material={materials["building"]}
            castShadow
            receiveShadow
          >
            <customOtherShaderMaterial attach="material" />
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh> */}
          {/* //#region 
          <mesh
            geometry={nodes.building001.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          <mesh
            geometry={nodes.building002.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building003
          <mesh
            geometry={nodes.building003.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building004
          <mesh
            geometry={nodes.building004.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building005
          <mesh
            geometry={nodes.building005.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building006
          <mesh
            geometry={nodes.building006.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building007
          <mesh
            geometry={nodes.building007.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building008
          <mesh
            geometry={nodes.building008.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building009
          <mesh
            geometry={nodes.building009.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building010
          <mesh
            geometry={nodes.building010.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building011
          <mesh
            geometry={nodes.building011.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building012
          <mesh
            geometry={nodes.building012.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building013
          <mesh
            geometry={nodes.building013.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building014
          <mesh
            geometry={nodes.building014.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building015
          <mesh
            geometry={nodes.building015.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building016
          <mesh
            geometry={nodes.building016.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building017
          <mesh
            geometry={nodes.building017.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building018
          <mesh
            geometry={nodes.building018.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building019
          <mesh
            geometry={nodes.building019.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building020
          <mesh
            geometry={nodes.building020.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building021
          <mesh
            geometry={nodes.building021.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building022
          <mesh
            geometry={nodes.building022.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building023
          <mesh
            geometry={nodes.building023.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building024
          <mesh
            geometry={nodes.building024.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building025
          <mesh
            geometry={nodes.building025.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building026
          <mesh
            geometry={nodes.building026.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building027
          <mesh
            geometry={nodes.building027.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building028
          <mesh
            geometry={nodes.building028.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building029
          <mesh
            geometry={nodes.building029.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building030
          <mesh
            geometry={nodes.building030.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building031
          <mesh
            geometry={nodes.building031.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building032
          <mesh
            geometry={nodes.building032.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building033
          <mesh
            geometry={nodes.building033.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building034
          <mesh
            geometry={nodes.building034.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building035
          <mesh
            geometry={nodes.building035.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building036
          <mesh
            geometry={nodes.building036.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building037
          <mesh
            geometry={nodes.building037.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building038
          <mesh
            geometry={nodes.building038.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building039
          <mesh
            geometry={nodes.building039.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building040
          <mesh
            geometry={nodes.building040.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building041
          <mesh
            geometry={nodes.building041.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building042
          <mesh
            geometry={nodes.building042.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building043
          <mesh
            geometry={nodes.building043.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building044
          <mesh
            geometry={nodes.building044.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building045
          <mesh
            geometry={nodes.building045.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building046
          <mesh
            geometry={nodes.building046.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building047
          <mesh
            geometry={nodes.building047.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building048
          <mesh
            geometry={nodes.building048.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building049
          <mesh
            geometry={nodes.building049.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building050
          <mesh
            geometry={nodes.building050.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building051
          <mesh
            geometry={nodes.building051.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building052
          <mesh
            geometry={nodes.building052.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building053
          <mesh
            geometry={nodes.building053.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building054
          <mesh
            geometry={nodes.building054.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building055
          <mesh
            geometry={nodes.building055.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building056
          <mesh
            geometry={nodes.building056.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building057
          <mesh
            geometry={nodes.building057.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building058
          <mesh
            geometry={nodes.building058.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building059
          <mesh
            geometry={nodes.building059.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building060
          <mesh
            geometry={nodes.building060.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building061
          <mesh
            geometry={nodes.building061.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building062
          <mesh
            geometry={nodes.building062.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building063
          <mesh
            geometry={nodes.building063.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building064
          <mesh
            geometry={nodes.building064.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building065
          <mesh
            geometry={nodes.building065.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building066
          <mesh
            geometry={nodes.building066.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building067
          <mesh
            geometry={nodes.building067.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building068
          <mesh
            geometry={nodes.building068.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building069
          <mesh
            geometry={nodes.building069.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building070
          <mesh
            geometry={nodes.building070.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building071
          <mesh
            geometry={nodes.building071.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building072
          <mesh
            geometry={nodes.building072.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building073
          <mesh
            geometry={nodes.building073.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building074
          <mesh
            geometry={nodes.building074.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building075
          <mesh
            geometry={nodes.building075.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building076
          <mesh
            geometry={nodes.building076.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building077
          <mesh
            geometry={nodes.building077.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building078
          <mesh
            geometry={nodes.building078.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building079
          <mesh
            geometry={nodes.building079.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building080
          <mesh
            geometry={nodes.building080.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building081
          <mesh
            geometry={nodes.building081.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building082
          <mesh
            geometry={nodes.building082.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building083
          <mesh
            geometry={nodes.building083.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building084
          <mesh
            geometry={nodes.building084.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building085
          <mesh
            geometry={nodes.building085.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building086
          <mesh
            geometry={nodes.building086.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building087
          <mesh
            geometry={nodes.building087.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building088
          <mesh
            geometry={nodes.building088.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building089
          <mesh
            geometry={nodes.building089.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building090
          <mesh
            geometry={nodes.building090.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building091
          <mesh
            geometry={nodes.building091.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // building092
          <mesh
            geometry={nodes.building092.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
          // ... continue until building093// ... continue until building093
          <mesh
            geometry={nodes.building093.geometry}
            material={materials["building"]}
            castShadow
            receiveShadow
          >
            <Edges scale={1} threshold={15} color="#AAA" />
          </mesh>
  //#endregion
         */}
        </Select>
        //ground
        <mesh
          geometry={nodes.ground.geometry}
          material={materials["ground"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.ground001.geometry}
          material={materials["ground"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.ground002.geometry}
          material={materials["ground"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.ground003.geometry}
          material={materials["ground"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.ground004.geometry}
          material={materials["ground"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        //road
        <mesh
          geometry={nodes.road.geometry}
          material={materials["road"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        //site
        <mesh
          geometry={nodes.site.geometry}
          material={materials["site"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        //water
        <mesh
          geometry={nodes.water.geometry}
          material={materials["water"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.water001.geometry}
          material={materials["water"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        //green
        <mesh
          geometry={nodes.green.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green001.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green002.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green003.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green004.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green005.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green006.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green007.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green008.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
        <mesh
          geometry={nodes.green009.geometry}
          material={materials["green"]}
          castShadow
          receiveShadow
        >
          {/* <Edges scale={1} threshold={15} color="#fff" /> */}
        </mesh>
      </Select>
      {/* <primitive
        object={scene}
        {...props}
        castShadow
        receiveShadow
        onClick={(e) => console.log("click")}
      /> */}
    </group>
  );
}

useGLTF.preload("models/RhinoModel0316.glb");
