/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 road.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Road = (props) => {
	const { nodes } = useGLTF("models/road.glb");
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.mesh_0.geometry}>
				<meshStandardMaterial color='#666' side={2} />
			</mesh>
		</group>
	);
};

useGLTF.preload("models/road.glb");
